// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrate necesita una conexión de sesión estable; el pooler de transacciones
    // (DATABASE_URL, usado en runtime por la app) no soporta el advisory lock que usa Migrate.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
